// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIc2jnP1SLri_3skLfVH1_GxcX8ZfTbjQ',
    appId: '1:23107628194:web:803d80095b30ecc66a7bfb',
    messagingSenderId: '23107628194',
    projectId: 'federalschool-47496',
    authDomain: 'federalschool-47496.firebaseapp.com',
    databaseURL: 'https://federalschool-47496-default-rtdb.firebaseio.com',
    storageBucket: 'federalschool-47496.appspot.com',
    measurementId: 'G-RVWXXW8BTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXECv-6Qi4S_nZ_3Z-KnGjBZfRlZwep8s',
    appId: '1:23107628194:android:0587dff6edde252e6a7bfb',
    messagingSenderId: '23107628194',
    projectId: 'federalschool-47496',
    databaseURL: 'https://federalschool-47496-default-rtdb.firebaseio.com',
    storageBucket: 'federalschool-47496.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR4FQ2RfgvBG4NlgfW7owApMfDntiMDvM',
    appId: '1:23107628194:ios:32dc6c34f47f8fdc6a7bfb',
    messagingSenderId: '23107628194',
    projectId: 'federalschool-47496',
    databaseURL: 'https://federalschool-47496-default-rtdb.firebaseio.com',
    storageBucket: 'federalschool-47496.appspot.com',
    iosBundleId: 'com.tatdep.federalSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtIXh7lUadrn5ebJPi05nEg3uYJJsMP2o',
    appId: '1:23107628194:ios:012a7ffef472168d6a7bfb',
    messagingSenderId: '23107628194',
    projectId: 'federalschool-47496',
    databaseURL: 'https://federalschool-47496-default-rtdb.firebaseio.com',
    storageBucket: 'federalschool-47496.appspot.com',
    iosBundleId: 'com.tatdep.diplom.RunnerTests',
  );
}
